- name: Deploy to Azure Web App
uses: azure/webapps-deploy@v2
with:
  app-name: 'flytiger-app'
  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  package: .
  startup-command: sh startup.sh